### ISSUE TITLE
The training scripts for baselines.

### ISSUE THREAD

**Issue by ucaslcl** [hesedjds/SQUAT#3]
Hi, can u provide the training  scripts for some baselines, such as MSDN, GPS-Net, etc. 

It seems that relation predictors of these baselines are not complete.

**Comment by hesedjds** [comment]
Thanks for your interest. 
The other baselines, without SQUAT, are not implemented by us. This repository is developed on top of the scene graph benchmarking framework developed by [SHTUPLUS](https://github.com/SHTUPLUS/PySGG). 
Please refer the SHTUPLUS's repository for the other baselines and scripts.
